### ISSUE TITLE
error python3 jcomp_pyserv.py

### ISSUE THREAD

**Issue by congaterori** [davidbombal/log4jminecraft#5]
Traceback (most recent call last):
  File "jcomp_pyserv.py", line 9, in <module>
    subprocess.run(["javac", "Log4jRCE.java"])
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'javac'

**Comment by davidbombal** [comment]
Did you run the other file first? You don't have the JDK installed.

**Comment by congaterori** [comment]
> JDK

so i need to install JDK in the server?
i already run log4j.py

**Comment by congaterori** [comment]
> Did you run the other file first? You don't have the JDK installed.

thank I fixed use
`sudo apt install default-jdk`
